import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// import BusinessNavbar from "@/components/nextBunny/BusinessNavbar";
// import { ThemeProvider } from "next-themes";
import { Toaster } from "@/components/ui/sonner";
import AuthProvider from "@/lib/AuthProvider";
import Providers from "@/store/Provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthProvider>
        <body
          className={`${geistSans.variable}1 ${geistMono.variable}1 antialiased`}
        >
          {/* <ThemeProvider attribute="class" defaultTheme="dark" enableSystem> */}

          {/* <BusinessNavbar></BusinessNavbar> */}
          <Providers>
            {children}
            <Toaster />
          </Providers>
          {/* </ThemeProvider> */}
        </body>
      </AuthProvider>
    </html>
  );
}
